before_script:
  - docker info
  - echo "build $CI_COMMIT_REF_NAME"

# after_script:
#   - echo "build done"

workflow:
  rules:
    - if: $CI_COMMIT_REF_NAME == "master" || $CI_COMMIT_REF_NAME == "test" || $CI_COMMIT_REF_NAME == "release" || $CI_COMMIT_REF_NAME =~ /^sprint/
      when: always
    - if: $CI_COMMIT_TAG
      when: always
    # - if: $CI_COMMIT_REF_NAME == "feat/ci" # test ci only
    #   when: always
    - when: never

stages:
  - build
  - deploy

build-tags:
  stage: build
  script:
    - make qucheng citag=${CI_COMMIT_TAG}
  only:
    - tags

build-custom:
  stage: build
  script:
    - make qucheng
  after_script:
    - echo "clean build"

build-api:
  stage: build
  script:
    - make api
  after_script:
    - echo "clean build"
  only:
    - test
    - master

deploy:
  stage: deploy
  script:
    - kubectl rollout restart deploy/qucheng -n cne-system --kubeconfig=$HOME/.kube/pre.kubeconfig
  only:
    - test
