version: '2'
services:
# mysql service for qucheng
  mysql:
    image: mysql:5.7
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - 'db:/var/lib/mysql'
    environment:
      - MYSQL_ROOT_PASSWORD=pass4Qucheng
      - MYSQL_DATABASE=qucheng

  qucheng:
    image: hub.qucheng.com/platform/qucheng:${TAG}
    container_name: qucheng
    ports:
      - '4080:80'
    volumes:
      - 'qucheng_data:/data'
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Qucheng
      - MYSQL_DB=qucheng
      - CNE_API_TOKEN=gwaN4KynqNqQoPD7eN8s
      - CNE_API_HOST=http://cne.internal-pre.chandao.net
      - CLOUD_API_HOST=http://cne-market.internal-pre.chandao.net
      - CLOUD_DEFAULT_CHANNEL=test
      - DEBUG=1
      - ENABLE_BACKEND=true

  qucheng-dev:
    image: hub.qucheng.com/platform/qucheng:${TAG}
    container_name: qucheng-dev
    ports:
      - '4081:80'
    volumes:
      - ./frontend:/apps/qucheng
      - ./docker/rootfs/apps/qucheng/config/my.php:/apps/qucheng/config/my.php
      - /root/.kube/config.dev:/root/.kube/config
      - /root/.config/helm/repositories.yaml.dev:/root/.config/helm/repositories.yaml
    depends_on:
      - mysql
    environment:
      - RUN_MODE="dev"
      - DEBUG=true
      - PHP_DEBUG=2
      - PAUSE=0
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pass4Qucheng
      - MYSQL_DB=qucheng
      - CNE_API_TOKEN=gwaN4KynqNqQoPD7eN8s
      - CNE_API_HOST=http://127.0.0.1:8087
      - CLOUD_API_HOST=https://api.qucheng.com
      - CLOUD_DEFAULT_CHANNEL=test
      - APP_DOMAIN=qc.yunop.com
      - CLOUD_SWITCH_CHANNEL=true

volumes:
  db:
    driver: local
  qucheng_data:
    driver: local
